# Generated by Django 2.2.2 on 2019-07-01 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
