# Generated by Django 2.2.2 on 2019-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=5)),
                ('is_order', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('last_transaction', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
